# Generated by Django 4.2 on 2023-04-21 03:54

from django.db import migrations, models
import miniurl.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=500)),
                ('mini_url', models.CharField(blank=True, default=miniurl.models.create_new_minurl, editable=False, max_length=20, unique=True)),
                ('visit_count', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
