# Generated by Django 4.2 on 2023-04-21 03:55

from django.db import migrations, models
import miniurl.models


class Migration(migrations.Migration):

    dependencies = [
        ('miniurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlpair',
            name='mini_url',
            field=models.CharField(blank=True, default=miniurl.models.create_new_minurl, editable=False, max_length=100, unique=True),
        ),
    ]
